### ISSUE TITLE
Follow the simple sample but fail

### ISSUE THREAD

**Issue by qwe661234** [robertmuth/Cwerg#27]
## issue reproducer
[Simple Example: Sieve of Eratosthenes](https://github.com/robertmuth/Cwerg/blob/master/Docs/getting_started.md#simple-example-sieve-of-eratosthenes)
```
FrontEndC/translate.py --mode 32 FrontEndC/TestData/sieve.c --cpp_args=-IStdLib > sieve.asm
```
I follow the simple sample in [document](https://github.com/robertmuth/Cwerg/blob/master/Docs/getting_started.md), but I got error. The error message shows below:

```
Traceback (most recent call last):
  File "/home/qwe661234/Cwerg/FrontEndC/translate.py", line 23, in <module>
    import canonicalize
  File "/home/qwe661234/Cwerg/FrontEndC/canonicalize.py", line 27, in <module>
    import transform_printf
  File "/home/qwe661234/Cwerg/FrontEndC/transform_printf.py", line 45, in <module>
    "write_u": MakePrintfStyleDecl("write_u", ["int", "unsigned"]),
  File "/home/qwe661234/Cwerg/FrontEndC/transform_printf.py", line 30, in MakePrintfStyleDecl
    MakeSimpleTypeDecl("fd", ["int"]), None, None)
  File "/home/qwe661234/Cwerg/FrontEndC/transform_printf.py", line 25, in MakeSimpleTypeDecl
    return c_ast.TypeDecl(name, [], common.GetCanonicalIdentifierType(type_names))
TypeError: TypeDecl.__init__() missing 1 required positional argument: 'type'
```

**Comment by robertmuth** [comment]
Which version of pycparser are you using?

It works with
python3-pycparser                   2.20-3  

The C frontend is no longer maintained since I am working on a new frontend.
So it is unlikely that I will adapt it to newer pycparser versions.
